---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bin-add
  labels:
    system: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    type: configuration

data:
  idam-pr-add: |
{{ include (print .Template.BasePath "/bin/_idam-pr-add.tpl") . | indent 4 }}
