---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hmcts.releaseName" . }}-bin-add
  labels:
    type: configuration
    app.kubernetes.io/name: {{ template "hmcts.releaseName" . }}-add
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
data:
  idam-pr-add: |
{{ include (print .Template.BasePath "/bin/_idam-pr-add.tpl") . | indent 4 }}
