api:
  url: https://idam-api.aat.platform.hmcts.net

web_public:
  url: https://idam-web-public.aat.platform.hmcts.net

memoryRequests: "128Mi"
cpuRequests: "25m"
memoryLimits: "1024Mi"
cpuLimits: "2500m"
