api:
  url: "{{ .Values.global.idamApiUrl }}"

web_public:
  url: "{{ .Values.global.idamWebUrl }}"

global:
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: https://idam-web-public.aat.platform.hmcts.net

memoryRequests: "128Mi"
cpuRequests: "25m"
memoryLimits: "1024Mi"
cpuLimits: "2500m"
