api:
  url: https://idam-api.aat.plaform.hmcts.net

web_public:
  url: https://idam-web-public.aat.platform.hmcts.net

user:
  username: idamOwner@hmcts.net
  password: Ref0rmIsFun

service:
  name: test-public-service
  redirect_uri: http://localhost/oauth2/receiver

memoryRequests: "512Mi"
cpuRequests: "25m"
memoryLimits: "1024Mi"
cpuLimits: "2500m"
